// ZForms
// Developed by PhantomBeta

#include "ZScript/MC_ZForms/BaseMenu.zsc"
#include "ZScript/MC_ZForms/Element.zsc"
#include "ZScript/MC_ZForms/Button.zsc"
#include "ZScript/MC_ZForms/BoxTextures.zsc"
#include "ZScript/MC_ZForms/BoundingBox.zsc"
#include "ZScript/MC_ZForms/Frame.zsc"
#include "ZScript/MC_ZForms/Label.zsc"
#include "ZScript/MC_ZForms/Handler.zsc"
#include "ZScript/MC_ZForms/Image.zsc"
#include "ZScript/MC_ZForms/UiEvent.zsc"